Await config flow steps.
TypeError: 'coroutine' object is not subscriptable.
Not very informative, but probably because we are not awaiting the next step,
just returning it straight back.